global_path_planner_node:
  ros__parameters:
    map_path: src/bringup/config/resize_IMG_4558v2((-500.000,-185.000),(43610.00,65000.00)).png
    min_x: -0.5
    max_x: 43.61
    min_y: -0.185
    max_y: 65.0
    diagonal_movement: true
    wall_search_range: 1
    wall_cost_waight: 1.0