localization_node:
  ros__parameters:
    start_pos: [5.2 , 61.0 , 3.14]
    show_debug_info: false
    predict_frequency: 50.0
    tf_rate: 10.0
    publish_tf: true
    enable_yaw_bias_estimation: true
    extend_state_step: 20
    pose_frame_id: "map"
    pose_additional_delay: 0.0
    pose_gate_dist: 100.0
    pose_smoothing_steps: 5
    twist_additional_delay: 0.0
    twist_gate_dist: 100.0
    twist_smoothing_steps: 1
    proc_stddev_vx_c: 0.5
    proc_stddev_vy_c: 0.5
    proc_stddev_wz_c: 0.1
    proc_stddev_yaw_c: 0.005
    twist_stddev_vx_c: 0.05
    twist_stddev_vy_c: 0.05
    twist_stddev_wz_c: 0.05