localization_node:
  ros__parameters:
    start_pos: [5.2 , 61.0 , 3.14]
    show_debug_info: false
    predict_frequency: 10.0
    tf_rate: 10.0
    publish_tf: true
    extend_state_step: 10
    pose_frame_id: "map"
    pose_additional_delay: 0.0
    pose_gate_dist: 10.0
    pose_smoothing_steps: 5
    twist_additional_delay: 0.0
    twist_gate_dist: 100.0
    twist_smoothing_steps: 1
    proc_stddev_vx_c: 2.0
    proc_stddev_vy_c: 2.0
    proc_stddev_wz_c: 2.0
    proc_stddev_yaw_c: 0.0
    twist_stddev_vx_c: 0.5
    twist_stddev_vy_c: 0.5
    twist_stddev_wz_c: 0.5