route_following_node:
  ros__parameters:
    control_period: 0.1
    max_vel: 0.5
    max_acc: 1.0
    max_ang_vel: 1.5
    max_ang_acc: 1.0
    vel_split_num: 7
    simulation_time: 1.0
    simulation_step: 10
    score_vel_norm_waight: 0.0
    score_goal_distance_waight: 1.0
    score_map_distance_waight: 0.2
    score_integral_error_waight: 0.2