route_following_node:
  ros__parameters:
    control_period: 0.1
    max_vel: 0.5
    max_acc: 1.0
    max_ang_vel: 1.5
    max_ang_acc: 1.0
    vel_split_num: 3
    simulation_time: 1.0
    simulation_step: 10
    collision_map_distance: 0.5
    ignore_map_distance: 1.0
    score_local_target_distance_waight: 1.0
    score_local_target_angle_waight: 0.5
    score_map_distance_waight: 0.2
    score_integral_error_waight: 0.4
    near_goal_control_distance: 0.5
    near_goal_control_pos_kp: 1.0
    near_goal_control_angle_kp: 1.0