route_following_node:
  ros__parameters:
    control_period: 0.2
    covariance_gain: 2.0
    max_vel: 1.0
    minimum_max_vel: 0.1
    max_acc: 2.0
    max_angle_vel: 1.5
    minimum_max_angle_vel: 0.1
    max_angle_acc: 1.0
    vel_split_num: 4
    simulation_time: 1.0
    simulation_step: 10
    collision_map_distance: 0.5
    ignore_map_distance: 1.0
    umap_timeout_stop_time: 2.0
    score_local_target_distance_waight: 1.0
    score_local_target_angle_waight: 0.5
    score_map_distance_waight: 0.3
    score_integral_error_waight: 0.35
    near_goal_control_distance: 0.5
    near_goal_control_pos_kp: 1.0
    near_goal_control_angle_kp: 1.0
    goal_distance: 0.1