umap_client_node:
  ros__parameters:
    period: 2.0
    server_ip: 192.168.11.8
    server_port: 50000
    device_id: TB01
    camera_number: 1
    resize_width: 320
    resize_height: 240
    canny_threshould1: 50.0
    canny_threshould2: 110.0
    umap_matching_distance: 2.0